spring.datasource.url=jdbc:mysql://localhost:3306/fullstack
spring.datasource.username=root
spring.datasource.password=Rahul2140@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# to create table dynamically
spring.jpa.hibernate.ddl-auto=update


